from cardopedia.kebab_case import kebab_case
from cardopedia.ordered_str_enum import OrderedStrEnum


class CardName(OrderedStrEnum):
    # Packs
    a_new_world = "A New World"
    humble_beginnings = "Humble Beginnings"
    seeking_wisdom = "Seeking Wisdom"
    reap_sow = "Reap & Sow"
    curious_cuisine = "Curious Cuisine"
    logic_and_reason = "Logic and Reason"
    explorers = "Explorers"
    order_and_structure = "Order and Structure"
    the_island = "The Island?"
    fresh_isle = "Fresh Isle"
    on_the_shore = "On the Shore"
    island_of_ideas = "Island of Ideas"
    grilling_and_brewing = "Grilling and Brewing"
    island_insights = "Island Insights"
    advanced_archipelago = "Advanced Archipelago"
    enclave_explorers = "Enclave Explorers"

    # Structures
    animal_pen = "Animal Pen"
    apple_tree = "Apple Tree"
    aquarium = "Aquarium"
    banana_tree = "Banana Tree"
    berry_bush = "Berry Bush"
    brickyard = "Brickyard"
    campfire = "Campfire"
    cathedral = "Cathedral"
    coin_chest = "Coin Chest"
    composter = "Composter"
    cotton_plant = "Cotton Plant"
    distillery = "Distillery"
    driftwood = "Driftwood"
    farm = "Farm"
    fish_trap = "Fish Trap"
    fishing_spot = "Fishing Spot"
    frigate = "Frigate"
    garden = "Garden"
    gold_deposit = "Gold Deposit"
    gold_mine = "Gold Mine"
    greenhouse = "Greenhouse"
    house = "House"
    iron_deposit = "Iron Deposit"
    iron_mine = "Iron Mine"
    lumber_camp = "Lumber Camp"
    market = "Market"
    mess_hall = "Mess Hall"
    pirate_boat = "Pirate Boat"
    quarry = "Quarry"
    rock = "Rock"
    rowboat = "Rowboat"
    sand_quarry = "Sand Quarry"
    sawmill = "Sawmill"
    shed = "Shed"
    shell_chest = "Shell Chest"
    sloop = "Sloop"
    smelter = "Smelter"
    soil = "Soil"
    spring = "Spring"
    stove = "Stove"
    strange_portal = "Strange Portal"
    sugar_cane = "Sugar Cane"
    temple = "Temple"
    travelling_cart = "Travelling Cart"
    treasure_chest = "Treasure Chest"
    tree = "Tree"
    warehouse = "Warehouse"

    # Humans
    baby = "Baby"
    dog = "Dog"
    explorer = "Explorer"
    fisher = "Fisher"
    friendly_pirate = "Friendly Pirate"
    militia = "Militia"
    swordsman = "Swordsman"
    trained_monkey = "Trained Monkey"
    villager = "Villager"

    # Resources
    bone = "Bone"
    bottle_of_water = "Bottle of Water"
    brick = "Brick"
    charcoal = "Charcoal"
    coin = "Coin"
    corpse = "Corpse"
    cotton = "Cotton"
    empty_bottle = "Empty Bottle"
    fabric = "Fabric"
    fishing_rod = "Fishing Rod"
    flint = "Flint"
    glass = "Glass"
    gold_bar = "Gold Bar"
    gold_ore = "Gold Ore"
    golden_goblet = "Golden Goblet"
    goop = "Goop"
    iron_bar = "Iron Bar"
    iron_ore = "Iron Ore"
    island_relic = "Island Relic"
    key = "Key"
    map = "Map"
    old_tome = "Old Tome"
    plank = "Plank"
    poop = "Poop"
    rope = "Rope"
    sacred_chest = "Sacred Chest"
    sacred_key = "Sacred Key"
    sail = "Sail"
    sand = "Sand"
    sandstone = "Sandstone"
    shell = "Shell"
    spear = "Spear"
    stick = "Stick"
    stone = "Stone"
    sword = "Sword"
    treasure_map = "Treasure Map"
    wood = "Wood"

    # Ideas

    # # Ideas Mainland
    idea_animal_pen = "Idea: Animal Pen"
    idea_brick = "Idea: Brick"
    idea_brickyard = "Idea: Brickyard"
    idea_campfire = "Idea: Campfire"
    idea_chicken = "Idea: Chicken"
    idea_coin_chest = "Idea: Coin Chest"
    idea_cooked_meat = "Idea: Cooked Meat"
    idea_farm = "Idea: Farm"
    idea_frittata = "Idea: Frittata"
    idea_fruit_salad = "Idea: Fruit Salad"
    idea_garden = "Idea: Garden"
    idea_growth = "Idea: Growth"
    idea_house = "Idea: House"
    idea_iron_bar = "Idea: Iron Bar"
    idea_iron_mine = "Idea: Iron Mine"
    idea_lumber_camp = "Idea: Lumber Camp"
    idea_market = "Idea: Market"
    idea_milkshake = "Idea: Milkshake"
    idea_offspring = "Idea: Offspring"
    idea_omelette = "Idea: Omelette"
    idea_plank = "Idea: Plank"
    idea_quarry = "Idea: Quarry"
    idea_sawmill = "Idea: Sawmill"
    idea_shed = "Idea: Shed"
    idea_smelter = "Idea: Smelter"
    idea_spear = "Idea: Spear"
    idea_stew = "Idea: Stew"
    idea_stick = "Idea: Stick"
    idea_stove = "Idea: Stove"
    idea_sword = "Idea: Sword"
    idea_temple = "Idea: Temple"
    idea_warehouse = "Idea: Warehouse"

    # # Ideas Island
    idea_aquarium = "Idea: Aquarium"
    idea_bottle_of_rum = "Idea: Bottle of Rum"
    idea_cathedral = "Idea: Cathedral"
    idea_ceviche = "Idea: Ceviche"
    idea_charcoal = "Idea: Charcoal"
    idea_coin = "Idea: Coin"
    idea_composter = "Idea: Composter"
    idea_distillery = "Idea: Distillery"
    idea_empty_bottle = "Idea: Empty Bottle"
    idea_fabric = "Idea: Fabric"
    idea_fish_trap = "Idea: Fish Trap"
    idea_fishing_rod = "Idea: Fishing Rod"
    idea_frigate = "Idea: Frigate"
    idea_glass = "Idea: Glass"
    idea_gold_bar = "Idea: Gold Bar"
    idea_gold_mine = "Idea: Gold Mine"
    idea_greenhouse = "Idea: Greenhouse"
    idea_mess_hall = "Idea: Mess Hall"
    idea_rope = "Idea: Rope"
    idea_rowboat = "Idea: Rowboat"
    idea_sacred_key = "Idea: Sacred Key"
    idea_sail = "Idea: Sail"
    idea_sand_quarry = "Idea: Sand Quarry"
    idea_sandstone = "Idea: Sandstone"
    idea_seafood_stew = "Idea: Seafood Stew"
    idea_shell_chest = "Idea: Shell Chest"
    idea_sloop = "Idea: Sloop"
    idea_sushi = "Idea: Sushi"
    idea_tamago_sushi = "Idea: Tamago Sushi"

    # Food
    apple = "Apple"
    banana = "Banana"
    berry = "Berry"
    bottle_of_rum = "Bottle of Rum"
    cane_sugar = "Cane Sugar"
    carrot = "Carrot"
    ceviche = "Ceviche"
    chili_pepper = "Chili Pepper"
    cooked_crab = "Cooked Crab"
    cooked_meat = "Cooked Meat"
    egg = "Egg"
    frittata = "Frittata"
    fruit_salad = "Fruit Salad"
    grilled_fish = "Grilled Fish"
    lime = "Lime"
    milk = "Milk"
    milkshake = "Milkshake"
    mushroom = "Mushroom"
    omelette = "Omelette"
    onion = "Onion"
    potato = "Potato"
    raw_crab_meat = "Raw Crab Meat"
    raw_fish = "Raw Fish"
    raw_meat = "Raw Meat"
    seafood_stew = "Seafood Stew"
    seaweed = "Seaweed"
    stew = "Stew"
    sushi = "Sushi"
    tamago_sushi = "Tamago Sushi"

    # Mobs
    bear = "Bear"
    chicken = "Chicken"
    cow = "Cow"
    crab = "Crab"
    demon = "Demon"
    demon_lord = "Demon Lord"
    giant_rat = "Giant Rat"
    goblin = "Goblin"
    kraken = "Kraken"
    momma_crab = "Momma Crab"
    monkey = "Monkey"
    parrot = "Parrot"
    pirate = "Pirate"
    rabbit = "Rabbit"
    rat = "Rat"
    seagull = "Seagull"
    skeleton = "Skeleton"
    slime = "Slime"
    small_slime = "Small Slime"
    snake = "Snake"
    tentacle = "Tentacle"
    tiger = "Tiger"
    wolf = "Wolf"

    # Locations
    catacombs = "Catacombs"
    cave = "Cave"
    forest = "Forest"
    graveyard = "Graveyard"
    jungle = "Jungle"
    mountain = "Mountain"
    old_village = "Old Village"
    plains = "Plains"

    # Fish
    cod = "Cod"
    eel = "Eel"
    mackerel = "Mackerel"
    shark = "Shark"
    tuna = "Tuna"

    # Rumors
    rumor_eel_bait = "Rumor: Eel Bait"
    rumor_shark_bait = "Rumor: Shark Bait"
    rumor_the_island = "Rumor: The Island"
    rumor_tuna_bait = "Rumor: Tuna Bait"

    def kebab(self):
        return kebab_case(self.value)

    def html_img(self):
        return f'<img class="card-image" src="images/{self.kebab()}.png" alt="{self.value} card" />'

    def html_link(self):
        return f'<a href="#{self.kebab()}" class="card-link">{self.html_img()}</a>'

    def html_button(self):
        return f'<button id="{self.kebab()}" class="card"><span class="card-name">{self.value}</span>{self.html_img()}</button>'
